export {default as Navbar} from './Navbar/Navbar'
export {default as Home} from './Home/Home'
export {default as GameDetailsPage} from './GameDetailPage/GameDetailsPage'
export {default as Search} from './Search/Search'
export {default as NoMatch} from './NoMatch/NoMatch'
export {default as Footer} from './Footer/Footer'